version: '3.8'

services:
  aws-lab:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - DATABASE_URL = postgresql://thesill_owner:qy8XiUg9Adkr@ep-silent-meadow-a16z7b9s.ap-southeast-1.aws.neon.tech/aws-test?sslmode=require
